import {createIcons,LayoutDashboard,House,BookOpen,Sprout,Users,Layers,Menu,Settings,Search,Mail,PanelBottom,ExternalLink,Eye,Save,Upload,ArrowUp,ArrowDown,Trash2,Plus} from 'lucide';
import {escapeHtml as e,validateWebsite} from './model.mjs';
const icons={LayoutDashboard,House,BookOpen,Sprout,Users,Layers,Menu,Settings,Search,Mail,PanelBottom,ExternalLink,Eye,Save,Upload,ArrowUp,ArrowDown,Trash2,Plus};
const editor=document.querySelector('[data-editor]'),status=document.querySelector('[data-status]');
const titles={dashboard:'Dashboard',home:'Homepage',community:'Community Programs',initiatives:'Our Initiatives',navigation:'Navigation',global:'Global Settings',seo:'SEO',contact:'Contact',footer:'Footer'};
let c,published,section='dashboard',dirty=false,busy=false;
const get=path=>path.split('.').reduce((v,k)=>v?.[k],c);
function set(path,value){const parts=path.split('.'),key=parts.pop();parts.reduce((v,k)=>v[k],c)[key]=value;}
const icon=name=>`<i data-lucide="${name}" aria-hidden="true"></i>`;
const field=(path,label,type='text')=>`<label class="rc-field">${e(label)}${type==='textarea'?`<textarea data-field="${e(path)}">${e(get(path))}</textarea>`:`<input type="${['image','url'].includes(type)?'text':type}" ${type==='image'?'list="website-images"':''} data-field="${e(path)}" value="${e(get(path))}" ${type==='url'?'placeholder="/page/ or https://..."':''}>`}</label>`;
const toggle=(path,label)=>`<label class="rc-switch"><input type="checkbox" data-field="${e(path)}" ${get(path)?'checked':''}>${e(label)}</label>`;
const fields=items=>`<div class="rc-field-grid">${items.map(x=>field(...x)).join('')}</div>`;
const block=(title,body)=>`<section class="rc-editor-section"><h2>${e(title)}</h2>${body}</section>`;
const reorder=(path,i,length,remove=false)=>`<div class="rc-actions"><button type="button" class="rc-icon" data-move="${e(path)}" data-index="${i}" data-direction="-1" title="Move up" aria-label="Move up" ${i===0?'disabled':''}>${icon('ArrowUp')}</button><button type="button" class="rc-icon" data-move="${e(path)}" data-index="${i}" data-direction="1" title="Move down" aria-label="Move down" ${i===length-1?'disabled':''}>${icon('ArrowDown')}</button>${remove?`<button type="button" class="rc-icon" data-delete="${e(path)}" data-index="${i}" title="Delete link" aria-label="Delete link">${icon('Trash2')}</button>`:''}</div>`;
const orderField=(path,i)=>`<label class="rc-field">Display Order<input type="number" min="1" max="${get(path).length}" value="${i+1}" data-order="${e(path)}" data-index="${i}"></label>`;
function links(path,max=6,featured=false){const list=get(path);return `<div class="website-links">${list.map((_item,i)=>`<div class="website-link-row">${field(`${path}.${i}.label`,'Label')}${field(`${path}.${i}.href`,'Destination')}${toggle(`${path}.${i}.enabled`,'Enabled')}${featured?field(`${path}.${i}.description`,'Description','textarea'):''}${orderField(path,i)}${reorder(path,i,list.length,true)}</div>`).join('')}</div><button type="button" data-add="${e(path)}" data-max="${max}" ${list.length>=max?'disabled':''}>${icon('Plus')}Add Link</button>`;}
function render(){
  if(!c)return;
  section=titles[location.hash.slice(1)]?location.hash.slice(1):section;
  document.querySelector('[data-section-title]').textContent=titles[section];
  document.querySelectorAll('[data-section]').forEach(el=>{if(el.dataset.section===section)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current');});
  let html='';
  if(section==='dashboard')html=`<div class="website-dashboard"><button type="button" data-go="home">Homepage${icon('House')}</button><button type="button" data-go="navigation">Navigation${icon('Menu')}</button><a href="/admin/ram/">RAM Control Center${icon('BookOpen')}</a><a href="/admin/sita/">SITA Control Center${icon('Sprout')}</a><button type="button" data-go="initiatives">Our Initiatives${icon('Layers')}</button><a href="/" target="_blank" rel="noreferrer">View Website${icon('ExternalLink')}</a></div>`;
  if(section==='community')html=block('Community Programs Control Center',`<p class="rc-muted">The dedicated Community Programs Control Center is not available yet.</p><a class="rc-button" href="/community-programs/" target="_blank" rel="noreferrer">${icon('ExternalLink')}View Community Programs</a>`);
  if(section==='home')html=block('Hero',fields([['home.eyebrow','Eyebrow'],['home.headline','Headline'],['home.description','Mission Copy','textarea'],['home.image','Hero Image','image']]))+block('Hero Buttons',fields([['home.primaryCta.label','Primary Button Label'],['home.primaryCta.href','Primary Button URL','url'],['home.secondaryCta.label','Secondary Button Label'],['home.secondaryCta.href','Secondary Button URL','url']])+toggle('home.primaryCta.enabled','Show Primary Button')+toggle('home.secondaryCta.enabled','Show Secondary Button'))+block('Homepage Sections',c.home.sections.map((s,i)=>`<div class="website-record-heading">${toggle(`home.sections.${i}.enabled`,s.label)}${orderField('home.sections',i)}${reorder('home.sections',i,c.home.sections.length)}</div>`).join(''))+block('Initiative Cards',fields([['home.initiativesHeading','Heading'],['home.initiativesIntro','Introduction','textarea']])+`<button type="button" data-go="initiatives">${icon('Layers')}Edit Initiative Cards</button>`)+block('About Summary',fields([['home.aboutHeading','Heading'],['home.aboutSummary','Summary','textarea'],['home.aboutRelated','Related Initiative','textarea'],['home.aboutImage','Related Initiative Image','image']]))+block('Why Choose Our Initiatives',field('home.valuesHeading','Section Heading')+c.home.values.map((_,i)=>fields([[`home.values.${i}.title`,'Title'],[`home.values.${i}.description`,'Description','textarea']])).join(''))+block('Featured Content',fields([['home.featuredHeading','Heading'],['home.featuredIntro','Introduction','textarea']])+links('home.featuredLinks',12,true))+block('Homepage SEO',fields([['home.seoTitle','Page Title'],['home.seoDescription','Description','textarea']]));
  if(section==='initiatives')html=block('Page Hero',fields([['initiativesPage.eyebrow','Eyebrow'],['initiativesPage.title','Title'],['initiativesPage.introduction','Introduction','textarea'],['initiativesPage.image','Hero Image','image']]))+block('Initiative Cards',c.initiativesPage.cards.map((card,i)=>`<div class="website-record"><div class="website-record-heading"><h3>${e(card.name)}</h3>${reorder('initiativesPage.cards',i,3)}</div>${fields([[`initiativesPage.cards.${i}.name`,'Name'],[`initiativesPage.cards.${i}.subtitle`,'Subtitle'],[`initiativesPage.cards.${i}.description`,'Description','textarea'],[`initiativesPage.cards.${i}.logo`,'Logo / Image','image'],[`initiativesPage.cards.${i}.href`,'Destination','url']])}${orderField('initiativesPage.cards',i)}${toggle(`initiativesPage.cards.${i}.enabled`,'Enabled')}${toggle(`initiativesPage.cards.${i}.featured`,'Show on Homepage')}</div>`).join(''))+block('Page SEO',fields([['initiativesPage.seoTitle','Page Title'],['initiativesPage.seoDescription','Description','textarea']]));
  if(section==='navigation')html=block('Primary Navigation',c.navigation.primary.map((_item,i)=>`<div class="website-link-row">${field(`navigation.primary.${i}.label`,'Label')}${field(`navigation.primary.${i}.href`,'Destination','url')}${toggle(`navigation.primary.${i}.enabled`,'Enabled')}${reorder('navigation.primary',i,6)}</div>`).join(''))+block('Our Initiatives Menu',c.navigation.groups.map((group,i)=>`<div class="website-record"><div class="website-record-heading"><h3>${e(group.name)}</h3>${reorder('navigation.groups',i,3)}</div>${fields([[`navigation.groups.${i}.name`,'Initiative Name'],[`navigation.groups.${i}.subtitle`,'Subtitle'],[`navigation.groups.${i}.logo`,'Logo / Icon','image'],[`navigation.groups.${i}.href`,'Destination','url']])}${orderField('navigation.groups',i)}${toggle(`navigation.groups.${i}.enabled`,'Enabled')}<h3 style="margin-top:24px">Featured Menu Links</h3>${links(`navigation.groups.${i}.links`)}</div>`).join(''))+block('Header CTAs',fields([['site.supportLabel','Support Button Label'],['site.donationUrl','Support / Donation URL','url'],['site.utilityLabel','Main Website Link Label']])+toggle('site.showUtility','Show Main Website Link'));
  if(section==='global')html=block('Organization & Identity',fields([['site.organizationName','Organization Name'],['site.organizationShortName','Organization Short Name'],['site.brandTitle','Brand Title'],['site.tagline','Tagline'],['site.mainWebsiteUrl','Main GOPAL Website URL','url'],['site.logo','Global Logo','image'],['site.favicon','Favicon','image']]));
  if(section==='seo')html=block('Site Defaults',fields([['seo.defaultTitle','Default Title'],['seo.titlePattern','Title Pattern ({title})'],['seo.description','Default Description','textarea'],['seo.verification','Search Console Verification'],['seo.socialImage','Default Social Image','image']])+`<label class="rc-field">Search Engine Visibility<select data-field="seo.robots"><option value="index, follow" ${c.seo.robots==='index, follow'?'selected':''}>Allow indexing</option><option value="noindex, nofollow" ${c.seo.robots==='noindex, nofollow'?'selected':''}>Do not index</option></select></label>`);
  if(section==='contact')html=block('Shared Contact Information',fields([['site.contactEmail','Email','email'],['site.contactPhone','Phone'],['site.address','Address','textarea']]));
  if(section==='footer')html=block('Footer Identity',fields([['footer.logo','Footer Logo','image'],['footer.description','Description','textarea'],['footer.copyright','Copyright Text']]))+block('Quick Links',links('footer.quickLinks',12))+block('Legal Links',links('footer.legalLinks',12))+block('Social Links',links('footer.socialLinks',12))+block('Shared Contact',`<button type="button" data-go="contact">${icon('Mail')}Edit Shared Contact Information</button>`);
  editor.innerHTML=html;createIcons({icons});
}
function message(text,error=false){status.textContent=text;status.dataset.error=String(error);}
function changed(){dirty=true;document.querySelector('[data-publication-state]').textContent='Unsaved changes';}
async function api(path,data){const response=await fetch('/api/website/'+path,{cache:'no-store',...(data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{})});const result=await response.json();if(!response.ok)throw Error(result.error||'Unable to save website settings.');return result;}
document.querySelector('[data-website-editor]').addEventListener('submit',event=>event.preventDefault());
editor.addEventListener('input',event=>{const path=event.target.dataset.field;if(!path)return;set(path,event.target.type==='checkbox'?event.target.checked:event.target.value);changed();});
editor.addEventListener('change',event=>{if(!event.target.dataset.order)return;const list=get(event.target.dataset.order),i=Number(event.target.dataset.index),target=Math.max(0,Math.min(list.length-1,Number(event.target.value)-1));if(Number.isInteger(target)){list.splice(target,0,list.splice(i,1)[0]);changed();render();}});
document.addEventListener('click',async event=>{
  const target=event.target.closest('button');if(!target)return;
  const go=target.dataset.section||target.dataset.go;if(go){section=go;location.hash=go;render();return;}
  if(!c||busy)return;
  if(target.dataset.move){const list=get(target.dataset.move),i=Number(target.dataset.index),j=i+Number(target.dataset.direction);if(j>=0&&j<list.length){[list[i],list[j]]=[list[j],list[i]];changed();render();}return;}
  if(target.dataset.delete){if(!confirm('Delete this link?'))return;get(target.dataset.delete).splice(Number(target.dataset.index),1);changed();render();return;}
  if(target.dataset.add){const list=get(target.dataset.add);if(list.length<Number(target.dataset.max)){list.push({label:'New Link',href:'/',enabled:true,...(target.dataset.add==='home.featuredLinks'?{description:''}:{})});changed();render();}return;}
  const action=target.dataset.action;if(!action)return;
  let previewWindow;
  try{
    validateWebsite(c);
    if(action==='preview')previewWindow=window.open('about:blank','_blank');
    busy=true;document.querySelectorAll('[data-action]').forEach(b=>b.disabled=true);
    const result=await api(action==='publish'?'publish':'draft',{content:c,revision:published.updatedAt});
    c=result.content;if(action==='publish')published=structuredClone(c);dirty=false;
    document.querySelector('[data-publication-state]').textContent=action==='publish'?'Published':'Draft saved';
    message(action==='publish'?'Website changes published.':'Draft saved.');
    if(action==='preview'){const path=section==='initiatives'?'/programs/':'/';if(previewWindow){previewWindow.opener=null;previewWindow.location=path+'?websitePreview=draft';}else message('Draft saved. Please allow popups to open the preview.',true);}
  }catch(error){previewWindow?.close();message(error.message,true);}finally{busy=false;document.querySelectorAll('[data-action]').forEach(b=>b.disabled=false);}
});
window.addEventListener('hashchange',render);
window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();}});
createIcons({icons});
async function load(){try{const result=await api('content');published=result.published;c=structuredClone(result.draft||published);document.querySelector('[data-publication-state]').textContent=result.draft?'Draft loaded':'Published';document.querySelectorAll('[data-action]').forEach(b=>b.disabled=false);render();}catch(error){editor.innerHTML='<p>Website settings could not be loaded.</p>';message(error.message,true);}}
load();
