import { createIcons,Plus,Pencil,Eye,Upload,Save,ArrowUp,ArrowDown,Archive,Trash2,Star,X,Image } from 'lucide';
import { escape as e,safeUrl,ordered,copy } from '../ram/model.mjs';
import { associations,validateTestimonials,testimonialMarkup } from './model.mjs';
import { bindTestimonialVideos } from './public.mjs';
const icons={Plus,Pencil,Eye,Upload,Save,ArrowUp,ArrowDown,Archive,Trash2,Star,X,Image};
export function initTestimonialsAdmin(root,initiative,programs=[],media=[]) {
  const abort=new AbortController();let c,revision,online=false,alive=true,dirty=false;
  const btn=(label,action,id='',symbol='')=>`<button type="button" data-t-action="${action}" data-id="${e(id)}">${symbol?`<i data-lucide="${symbol}" aria-hidden="true"></i>`:''}${e(label)}</button>`;
  const input=(key,label,value,type='text')=>`<label class="rc-field">${e(label)}${type==='textarea'?`<textarea name="${key}" rows="4">${e(value||'')}</textarea>`:`<input name="${key}" type="${type}" value="${e(value||'')}">`}</label>`;
  const toggle=(key,label,value)=>`<label class="rc-switch"><input name="${key}" type="checkbox" role="switch" ${value?'checked':''}>${label}</label>`;
  const message=(text,error=false)=>{const n=root.querySelector('[data-t-status]');if(n){n.textContent=text;n.dataset.error=String(error);}};
  async function api(action,data) { const r=await fetch('/api/testimonials/'+action,{cache:'no-store',signal:abort.signal,...(data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{})});const b=await r.json();if(!r.ok)throw Error(b.error||'Testimonials are unavailable.');return b; }
  const mine=()=>ordered(c.records).filter(r=>associations(r).includes(initiative));
  function render() {
    if(!alive||!c)return;
    const settings=c.settings[initiative];root.innerHTML=`<div class="rc-section-top"><div><h2>Testimonials</h2><p>Publish genuine participant feedback only with permission.</p></div>${btn('Add Testimonial','add','','Plus')}</div><p data-t-status class="rc-status" role="status"></p><form data-t-settings><div class="rc-field-grid">${input('heading','Section Heading',settings.heading)}${input('intro','Supporting Text',settings.intro)}${input('count','Number of Testimonials',settings.count,'number')}${toggle('visible','Show Public Section',settings.visible)}</div><button type="submit">Apply Section Settings</button></form><div class="rc-actions" style="margin-block:20px">${btn('Save Draft','save','','Save')}${btn('Preview Section','preview-section','','Eye')}${btn('Publish Testimonials','publish','','Upload')}</div>${['Published','Draft','Archived'].map(group=>`<div class="rc-group"><h3>${group} Testimonials</h3><div class="rc-list">${mine().filter(r=>group==='Archived'?r.archived:!r.archived&&(group==='Published'?r.published:!r.published)).map(r=>`<article class="rc-record">${r.image?`<img src="${e(safeUrl(r.image))}" alt="${e(r.imageAlt||r.displayName)}">`:'<i data-lucide="Star" aria-hidden="true"></i>'}<div><h3>${e(r.displayName||'Untitled Testimonial')}</h3><p>${e(r.testimonialText?.slice(0,140))}</p><span class="rc-badge">${r.consentConfirmed?'Consent Confirmed':'Consent Required'}</span>${r.featured?'<span class="rc-badge">Featured</span>':''}</div><div class="rc-actions">${btn('Edit','edit',r.id,'Pencil')}${btn('Preview','preview',r.id,'Eye')}${!r.archived?btn(r.published?'Unpublish':'Publish','toggle-publish',r.id,'Upload')+btn(r.featured?'Unfeature':'Feature','feature',r.id,'Star'):''}${btn('Move Up','up',r.id,'ArrowUp')}${btn('Move Down','down',r.id,'ArrowDown')}${btn(r.archived?'Restore':'Archive','archive',r.id,'Archive')}${btn('Delete','delete',r.id,'Trash2')}</div></article>`).join('')||'<p class="rc-muted">No testimonials yet. Add real feedback when consent is available.</p>'}</div></div>`).join('')}`;createIcons({icons});
  }
  function dialog(html) { const d=document.createElement('dialog');d.className='testimonial-editor';d.innerHTML=html;document.body.append(d);d.addEventListener('close',()=>d.remove(),{once:true});d.querySelectorAll('[data-t-close]').forEach(b=>b.onclick=()=>d.close());d.showModal();createIcons({icons});return d; }
  function edit(id) {
    const original=c.records.find(r=>r.id===id);const r=copy(original||{id:'testimonial-'+crypto.randomUUID(),initiative:[initiative],program:'',displayName:'',role:'',city:'',testimonialText:'',image:'',imageAlt:'',videoUrl:'',date:'',featured:false,published:false,displayOrder:c.records.length+1,consentConfirmed:false,archived:false});
    const d=dialog(`<form data-t-record><div class="rc-dialog-heading"><h2>${original?'Edit':'Add'} Testimonial</h2><button type="button" class="rc-icon" data-t-close aria-label="Close editor"><i data-lucide="X"></i></button></div><div class="rc-field-grid">${input('displayName','Display Name',r.displayName)}${input('role','Role / Relationship',r.role)}${input('city','City',r.city)}${input('testimonialText','Quote',r.testimonialText,'textarea')}<label class="rc-field">Related Program<select name="program"><option value="">No Program</option>${programs.map(p=>`<option value="${e(p.id)}" ${r.program===p.id?'selected':''}>${e(p.title)}</option>`).join('')}</select></label>${input('date','Date',r.date,'date')}${input('videoUrl','YouTube Testimonial URL',r.videoUrl,'url')}${input('displayOrder','Display Order',r.displayOrder,'number')}${toggle('consentConfirmed','Consent Confirmed',r.consentConfirmed)}${toggle('published','Published',r.published)}${toggle('featured','Featured',r.featured)}</div><fieldset><legend>Initiative Associations</legend>${['RAM','SITA','COMMUNITY'].map(i=>`<label class="rc-switch"><input type="checkbox" name="initiative" value="${i}" ${associations(r).includes(i)?'checked':''}>${i}</label>`).join('')}</fieldset><h3>Participant Image (Optional)</h3><img data-t-image-preview src="${e(safeUrl(r.image,'/logos/'+initiative.toLowerCase()+'-logo.png'))}" alt="Image preview" style="width:100px;height:100px;object-fit:contain"><div class="rc-actions"><label class="rc-upload">Upload Image<input type="file" data-t-upload accept="image/png,image/jpeg,image/webp"></label><button type="button" data-t-clear>Remove Image</button></div><div class="rc-media-grid">${media.map(m=>`<button type="button" data-t-image="${e(m.url)}"><img src="${e(safeUrl(m.url))}" alt="${e(m.alt||m.name)}"><span>${e(m.name)}</span></button>`).join('')}</div>${input('imageAlt','Image Alt Text',r.imageAlt)}<p data-t-error role="alert"></p><div class="rc-dialog-footer"><button type="button" data-t-close>Cancel</button><button type="submit" class="rc-primary">Apply Changes</button></div></form>`);
    function image(url){r.image=url;d.querySelector('[data-t-image-preview]').src=safeUrl(url,'/logos/'+initiative.toLowerCase()+'-logo.png');}
    d.querySelectorAll('[data-t-image]').forEach(b=>b.onclick=()=>image(b.dataset.tImage));d.querySelector('[data-t-clear]').onclick=()=>image('');
    d.querySelector('[data-t-upload]').onchange=async event=>{const file=event.target.files[0];if(!file)return;const error=d.querySelector('[data-t-error]');try {if(file.size>5*1024*1024)throw Error('Choose an image smaller than 5 MB.');const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});const resp=await fetch('/api/testimonials/upload',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({data,name:file.name})});const b=await resp.json();if(!resp.ok)throw Error(b.error);image(b.url);media.push(b);}catch(err){error.textContent=err.message;}};
    d.querySelector('form').onsubmit=event=>{event.preventDefault();const f=new FormData(event.target);for(const key of ['displayName','role','city','testimonialText','program','date','videoUrl','imageAlt'])r[key]=String(f.get(key)||'');r.initiative=f.getAll('initiative');r.displayOrder=Number(f.get('displayOrder'));for(const key of ['consentConfirmed','published','featured'])r[key]=f.has(key);const candidate=copy(c);candidate.records=original?candidate.records.map(x=>x.id===id?r:x):[...candidate.records,r];try{validateTestimonials(candidate);c=candidate;dirty=true;d.close();render();message('Changes applied. Save Draft or Publish Testimonials.');}catch(err){d.querySelector('[data-t-error]').textContent=err.message;}};
  }
  function preview(id) {const records=id?[c.records.find(r=>r.id===id)]:mine().filter(r=>!r.archived);const d=dialog(`<div class="rc-dialog-heading"><h2>Admin-only Testimonial Preview</h2><button class="rc-icon" data-t-close aria-label="Close preview"><i data-lucide="X"></i></button></div>${testimonialMarkup({settings:{...c.settings[initiative],visible:true},records:records.slice(0,6)},programs)||'<p>No testimonials to preview.</p>'}`);bindTestimonialVideos(d);}
  async function save(publish=false){if(!c)throw Error('Testimonials have not loaded.');validateTestimonials(c);const b=await api(publish?'publish':'draft',{content:c,revision});if(!alive)return;c=b.content;if(publish)revision=c.updatedAt;dirty=false;render();message(publish?(online?'Testimonials published to the live website.':'Testimonials published to the local website.'):'Testimonial draft saved. Public feedback is unchanged.');}
  root.addEventListener('click',async event=>{const b=event.target.closest('[data-t-action]');if(!b||!c)return;const action=b.dataset.tAction,id=b.dataset.id,r=c.records.find(r=>r.id===id);try {if(action==='add'||action==='edit')return edit(id);if(action==='preview'||action==='preview-section')return preview(id);if(action==='save'||action==='publish')return await save(action==='publish');if(action==='toggle-publish'){if(!r.published&&(!r.consentConfirmed||!r.displayName.trim()||!r.testimonialText.trim()))throw Error('Confirm consent and complete the quote before publishing.');r.published=!r.published;}if(action==='feature')r.featured=!r.featured;if(action==='archive'){r.archived=!r.archived;r.published=false;}if(action==='delete'){if(!confirm('Delete this testimonial?'))return;c.records=c.records.filter(x=>x.id!==id);}if(action==='up'||action==='down'){const rows=mine();const i=rows.findIndex(x=>x.id===id),j=i+(action==='up'?-1:1);if(j>=0&&j<rows.length){[rows[i],rows[j]]=[rows[j],rows[i]];rows.forEach((x,n)=>x.displayOrder=n+1);}}dirty=true;render();message('Unpublished changes.');}catch(err){message(err.message,true);}},{signal:abort.signal});
  root.addEventListener('submit',event=>{if(!event.target.matches('[data-t-settings]'))return;event.preventDefault();const f=new FormData(event.target);c.settings[initiative]={heading:String(f.get('heading')),intro:String(f.get('intro')),visible:f.has('visible'),count:Math.max(3,Math.min(6,Number(f.get('count'))||6))};dirty=true;message('Section settings applied to your draft.');},{signal:abort.signal});
  root.innerHTML='<p>Loading testimonials...</p>';api('content').then(b=>{if(!alive)return;online=Boolean(b.online);for(const item of b.media||[])if(!media.some(m=>m.url===item.url))media.push(item);c=b.draft||b.published;revision=b.published.updatedAt;render();}).catch(err=>{if(alive)root.innerHTML=`<p role="alert">${e(err.message)}</p>`;});
  const unload=event=>{if(dirty)event.preventDefault();};window.addEventListener('beforeunload',unload,{signal:abort.signal});
  return {save,preview:()=>preview(''),hasUnsaved:()=>dirty,destroy:()=>{alive=false;abort.abort();document.querySelectorAll('.testimonial-editor').forEach(d=>d.close());root.replaceChildren();}};
}
