import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createFileCms} from '../src/server/cms.mjs';
import {copy} from '../src/lib/sita/model.mjs';
const sita=JSON.parse(await readFile(new URL('../public/content/sita.json',import.meta.url),'utf8')),testimonials=JSON.parse(await readFile(new URL('../src/data/testimonials.json',import.meta.url),'utf8'));
export function memoryBucket(){const map=new Map();let sequence=0;return {map,async get(key){const x=map.get(key);return x?{etag:x.etag,json:async()=>JSON.parse(x.value),body:x.value,httpMetadata:x.metadata}:null;},async put(key,value,options={}){const previous=map.get(key),only=options.onlyIf;if(only instanceof Headers&&only.get('If-None-Match')==='*'&&previous)return null;if(only?.etagMatches&&previous?.etag!==only.etagMatches)return null;const etag='test-etag-'+(++sequence);map.set(key,{etag,value,metadata:options.httpMetadata});return {etag};}};}
function harness(){const bucket=memoryBucket(),origin='https://cms.example.org';let allowed=true;const cms=createFileCms({bucket,seeds:{sita,testimonials},authorize:async()=>allowed,origin});const call=(path,data,requestOrigin=origin)=>cms.handle(new Request(origin+path,{method:data?'POST':'GET',headers:data?{Origin:requestOrigin,'Content-Type':'application/json'}:{},...(data?{body:JSON.stringify(data)}:{})}));return {bucket,cms,call,deny:()=>{allowed=false;}};}
test('online drafts remain private and publishing persists across independent CMS instances',async()=>{const h=harness(),c=copy(sita);c.hero.tagline='Synthetic draft test';const p={content:c,revision:sita.updatedAt};assert.equal((await h.call('/api/sita/draft',p)).status,200);assert.equal((await(await h.call('/content/sita.json')).json()).hero.tagline,sita.hero.tagline);assert.equal((await(await h.call('/api/sita/content')).json()).draft.hero.tagline,'Synthetic draft test');assert.equal((await h.call('/api/sita/publish',p)).status,200);const other=createFileCms({bucket:h.bucket,seeds:{sita,testimonials},authorize:async()=>true,origin:'https://cms.example.org'});assert.equal((await other.published('sita')).hero.tagline,'Synthetic draft test');assert.equal((await h.call('/api/sita/publish',p)).status,409);});
test('online content writes require authorization and exact same origin',async()=>{const h=harness();assert.equal((await h.call('/api/sita/publish',{content:sita,revision:sita.updatedAt},'https://other.example.org')).status,403);h.deny();assert.equal((await h.call('/api/sita/content')).status,401);assert.equal((await h.call('/api/testimonials/publish',{content:testimonials,revision:testimonials.updatedAt})).status,401);});
test('private drafts, upload originals and unconsented testimonials cannot leak publicly',async()=>{const h=harness(),c=copy(testimonials);c.records=[{id:'test-only-draft',initiative:['RAM','SITA'],displayName:'Synthetic private draft',testimonialText:'Synthetic test data only',published:false,consentConfirmed:false,displayOrder:1}];assert.equal((await h.call('/api/testimonials/draft',{content:c,revision:testimonials.updatedAt})).status,200);assert.ok(!JSON.stringify(await(await h.call('/api/testimonials/public?initiative=SITA')).json()).includes('Synthetic private draft'));const image=await(await h.call('/api/testimonials/upload',{data:'iVBORw0KGgo=',name:'Test Image'})).json();h.deny();assert.equal((await h.call(image.url)).status,404);});
test('conditional writes prevent simultaneous publishing from silently overwriting one another',async()=>{const h=harness(),one=copy(sita),two=copy(sita);one.hero.tagline='One';two.hero.tagline='Two';const a=h.call('/api/sita/publish',{content:one,revision:sita.updatedAt}),b=h.call('/api/sita/publish',{content:two,revision:sita.updatedAt});const statuses=[(await a).status,(await b).status].sort();assert.deepEqual(statuses,[200,409]);});
test('CMS storage failure never acknowledges publication and rejects unsafe image uploads',async()=>{const cms=createFileCms({bucket:{get:async()=>{throw Error('Storage unavailable');}},seeds:{sita,testimonials},authorize:async()=>true,origin:'https://cms.example.org'});const r=await cms.handle(new Request('https://cms.example.org/api/sita/publish',{method:'POST',headers:{Origin:'https://cms.example.org','Content-Type':'application/json'},body:JSON.stringify({content:sita,revision:sita.updatedAt})}));assert.equal(r.status,503);const h=harness();assert.equal((await h.call('/api/sita/upload',{data:btoa('<svg onload="alert(1)"></svg>')})).status,503);});
test('hosted automatic feeds refresh without releases and preserve editorial overrides during outages',async()=>{
  const c=copy(sita),bucket=memoryBucket();c.videoSettings={...c.videoSettings,automatic:true,sourceType:'CHANNEL',channelId:'UCG_Yw9L5TGukTabIdhO5vFQ'};
  let time=1000000,calls=0,outage=false;
  const request=async()=>{calls++;if(outage)throw Error('Feed unavailable');return new Response('<feed><entry><yt:videoId>abcdefghijk</yt:videoId><title>Feed test</title></entry></feed>');};
  const cms=createFileCms({bucket,seeds:{sita:c,testimonials},authorize:async()=>true,origin:'https://cms.example.org',request,now:()=>time});
  assert.equal((await cms.published('sita')).videos[0].title,'Feed test');await cms.published('sita');assert.equal(calls,1);
  time+=600001;outage=true;assert.equal((await cms.published('sita')).videos.length,1);assert.equal(calls,2);
  c.videos=[{id:'yt-abcdefghijk',url:'https://www.youtube.com/watch?v=abcdefghijk',title:'Curated title',enabled:false}];
  const other=createFileCms({bucket,seeds:{sita:c,testimonials},authorize:async()=>true,origin:'https://cms.example.org',request,now:()=>time});
  assert.equal((await other.published('sita')).videos[0].title,'Curated title');assert.equal((await other.published('sita')).videos[0].enabled,false);
});
